import Link  from 'next/link';
import Image from 'next/image'



export const metadata = {
    title: "pageone of many",
    description: "Generated by create next app",
    // this discripiton is used to give context aboout this page to search engine bots
  };


export default function Home() {
    return (
      <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
        <h1> posts page</h1>
        <Link href="/"  legacyBehavior>
          <a>go to the home page</a>
        </Link>
        <Image
          src="https://fastly.picsum.photos/id/621/536/354.jpg?hmac=_8_0dSqKvqAOmC-OYdQNAd-gcWiXFDI9svR-kItggsg"
          width="500"
          height="500"
          alt="Picture of the author"
        />
      </div>
    );   
  }
  